### ISSUE TITLE
Documentation: Task List

### ISSUE THREAD

**Issue by joeconwaystk** [stablekernel/aqueduct#114]
- [x] Authentication
- [x] Database Migration
- [x] CORS Support
- [x] Testing
- [x] Using the Template tutorial
- [ ] OpenAPI Specification generation
- [x] PersistentStore Implementations
- [x] Improve Tutorial Navigation
- [x] Deployment Options (Heroku, EC2)
- [x] Debugging Aqueduct Applications

**Comment by erikist** [comment]
We should also have a section on debugging an aqueduct application.
